name: Hello World Workflow

on:
  # Triggers the workflow on push events
  push:
    branches: [ main ]
  # Also allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  hello-job:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        
      - name: 23f1002103@ds.study.iitm.ac.in
        run: echo "Hello, world!"
        
      - name: Current date
        run: date
